apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: siaga-secrets
spec:
  secretTemplates:
    - name: siaga-db-geo
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:yA1F+CqY9nnn,iv:aW0HI3hE99n6b9XOCprxJ+cC7RmvERalH88hOrx5TwA=,tag:5XTAXW3WcjWw7d/Hjh+Ynw==,type:str]
        password: ENC[AES256_GCM,data:QsfgcmtSp0nDtswC8gXyY5tjaECSsVmY4ZZbBgQKQzGeq77SuS4Sq6REQK6saKMN,iv:q4kzZb2vkQxrpUtb3Ht0scQK+TMYgbxccFeoTOcVeHE=,tag:GNVdxgNoWnGO9cxNMOyyCQ==,type:str]
    - name: siaga-db-core
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:/2jT8V0lQM74+A==,iv:Z3+R93SUP75w9T1vrfo7tGdHvxnRnpyavHuBgeL1hnA=,tag:ylcHvd4VZ94vIzl0oVlcXQ==,type:str]
        password: ENC[AES256_GCM,data:NV3aJcgrJTWhnlu4v4gymkJuLRgsJmzrt/9S8+v7qwqdbd8wZ8YT/vatjxEdDimm,iv:S1gaLNqlkaJePLd4h1wIY7z1/hirvtvOS5pqEvbt/gs=,tag:EI9e9bC1UkGKwj0oWhHYqA==,type:str]
    - name: siaga-db-alert
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:KMBTJB+gvW6B8Q8=,iv:LLZiIMuwdfo/yqQd6gBM+4i8J6mFCLu+/ynUgGcqlvY=,tag:2qwCyZtOzMhwth/egnf2sA==,type:str]
        password: ENC[AES256_GCM,data:Xf1oZ2aODez+t31LVXLNd0UiO9CNDg7hQs+3PZixpl+FkQKH/ACUrh5r5bh2k28p,iv:gS4DFU6gAzdrWpPkRwnv7w4hWl+CU0u6sFKcx+wAccg=,tag:ryhDYDeobbW0m7+WxMolUg==,type:str]
    - name: siaga-db-ai
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:2MlKQPX0o5k=,iv:Vjk2F53N4YpEgEZoQJFbOcf231ZHFPzsxsyUXG3IX1o=,tag:BfpdWSB1u4hqoHFRQMxPDw==,type:str]
        password: ENC[AES256_GCM,data:psHCB4u8hR26Ap7mtu4Gw6kjsUXNjXzy9Hq8X7Wy2AaqJIzxTMKcxWdwH+QhWh/3,iv:Vdb8lg6E9vCeNertY/8b6kvToeRUO9+solRDmKGOvPQ=,tag:jgaeM/hWYUzmgq3F8WKiFQ==,type:str]
    - name: siaga-db-tiles
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:qPuAWw0hWEmHvD8=,iv:2l2fZSKqeJgrt+YyIOtbdeZBQKRRFNkSfZJj7iaoPr4=,tag:QqCEQONG2YlhSKcvYDcyvQ==,type:str]
        password: ENC[AES256_GCM,data:Yj1IZiM3EDxNiiFdwAX2gRJfv0L2uaK0z60jec4Y9eVCedLh9DEC8nnKgCe5RVgO,iv:ucOIF95PEKwZImFSGoRsi/DRfMKRLHkZ2cCto9d+A6w=,tag:azkLCMg2d13I6FsuW6Vf0Q==,type:str]
    - name: siaga-garage
      stringData:
        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:9Pvwv/j4QUCcP3CrkIfzqw811Crce8CrsM8Ei8uKoqCYgN1jtQnIeUusbIjvKZT+aLkM2Xve9YPGyTN+FBMJBw==,iv:oUvGuqAmY0GrM/hq8/uD6is9NSIEexwrAGvNQTUuw6A=,tag:lXI7btHO+QNCJf9ze76BmA==,type:str]
        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:0QWhWuF1qeFoqoHFLMfLvcnNwavhVg67YRh/bP78qGIbbGXm9Q0m7XcIfDdfLFa2,iv:qo1pFh70gOWA0Y8wV0c5TBWhDLaQRMJtRr+OJUA0zU0=,tag:8PeG9FqWnU4wH04f1txpOg==,type:str]
        GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:rAbXnpnda/ZpOwWSLoFJ8drrxkl7MSj3EGqJIEvayUGDBE+7m/pnwmPTbp9O7IjS,iv:+iR3AI71UyP/c/wlGDXWdZE3nj6BhJBL8h70eyEdQC4=,tag:1lrRT0YO8fa8AT07syBOPQ==,type:str]
        GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:P4jXiNRA8Fnm5IEy8bE9eLkuesqihccxsi4=,iv:KfD6hrn+der1HaCRKnRV4W60WlVG2arIoLRExIsiLTI=,tag:HHVho7d6TUuCY2foUnfvHw==,type:str]
        GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:+gtbHIbQrgxxI1Jn8KitxXGu/VxE0IESCzDjIvW9sgbmjiRj5nufWsfLLPOaQudtTuWAYhEkyc1KnYuOR9d1Fw==,iv:qoTYQg8lLHkkj4ek/cyB2FqrfouM0GWhArj1hlwJLYo=,tag:04T4CMWT4rShmVwWPvA+mg==,type:str]
    - name: siaga-ingest
      stringData:
        OPENAQ_API_KEY: ENC[AES256_GCM,data:NtT7Wk7d4nIKXiLPzQ0uP20NqxKz5dWd47J7lrmittpDlM2LqttHzngfzg430asTaGvGMVKCpUxVX1oF3Y4Naw==,iv:Kuwh8cFD2rhg4fehP8L3WI89og4LPnfjAXf0yadCOIM=,tag:O11LcVI5YRt1YNV1cfTRhA==,type:str]
        FIRMS_MAP_KEY: ENC[AES256_GCM,data:AIXDowYSFlPU7jO5DuxY+OHHLsA2MOFBLrvszFEi0hc=,iv:SlVPNLz5U3IKngQvlbrrqKIJE0aZibqoy7pcYZolOTg=,tag:usfOVXsXsk107EBjshNU2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWEVGamNZaEY1d1ExSjJM
        TEVKT2ZMZzhUTG56L1FuSllrcThTbHJWejJvCmlWZ1JPM1BITHArNDdJa0E0TzVG
        bDBYWXNPR2daSkNBVWFPZjZGZzhPT0UKLS0tIDN1dHovTWhYMm0zKzlFYUUzb21I
        c1pFai9SZDhBRHpPY2t2M0xFNEdSVUkKpvVJOCnCVIEAh98mL4sRJDhYzUatQQyE
        /k2XzhGTDlRj1FY0iCrmH2EtSVWUDqPaUudiQ72/Iu8ZiKA57gNPmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zm7j84cz6ep8k5d9xzclcw462aasq80xyx539g2vt9nc64ym3svsktqg5c
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T14:44:56Z"
  mac: ENC[AES256_GCM,data:bPFXt2L1bnV6fTK4AJf+bex50T3zZlI0FjUVq+jONG21t5TpzW0wO0VeGc1cJfX9fytBEPNjzzEJ9tyj9dY1YQwdD69rXgK3/YtU1TvBI0opdVoDyYYDleEfE0TqVLAGV2A+L+9exPVK1odr0gTj42YxC/FvOeIpxgzGs1lDlSo=,iv:xWvKRD9K1Yv1NYR4cwqT4g21eLZ0thn1cuadcBXuVTg=,tag:SR13KgjowV2WYDpQQfGWKg==,type:str]
  version: 3.13.3
