apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: siaga-secrets
spec:
  secretTemplates:
    - name: siaga-db-geo
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:18vhu9cwe5ng,iv:0ngQcYbjxbjOPy4ZZSe33c0XQGWX56UhbdQ7fQGNpWo=,tag:SYs2iDocYMXy3roGm9Rl3w==,type:str]
        password: ENC[AES256_GCM,data:4OTgd9OmNbseedBWtvKsPdrMNsYkOKYzD9Ad87BAop2mnfhbJKqlicdBcepEpABl,iv:h60aKhvqSgvVjLEcqcCD2N96UfBX7nqlo8364IuN28o=,tag:k07KbitbhrQUKNjVl59toQ==,type:str]
    - name: siaga-db-core
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:VgazgZ1UUE5b+A==,iv:Q/MyelnYi+U3VBQ8mQqtKh6kMdNpHjwJSmBFAfuJ0aw=,tag:xP4HEW6uvMbKPrF2+yO/SA==,type:str]
        password: ENC[AES256_GCM,data:ol0i6VcioujeYhU/5H7qV50qWH28z139T8pCP4dUnDHX6VQxSMSW95mliCGGUQt4,iv:gi1hRfyibDeeWydJ4o4BZNFBePjBDGt8dqAqb9b+diU=,tag:KeEe07a2beqcYYDr+Fazfg==,type:str]
    - name: siaga-db-alert
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:58uJpHzJW/5JpX8=,iv:KBAPJN1Zcz5ofsUN5FpHNGT3ztNjBkblTxkcd32K9/Y=,tag:jDaRM1EdMTRzpbJF8M97BA==,type:str]
        password: ENC[AES256_GCM,data:uu16RFTQ+ufKFcqRvW4zejXIS5C18SJxiBtmPO14c94zVr8hceAZ3baCck9ptM0f,iv:ZGvEquU0YZ8vZ50diTH1U+dUgyuoHy96YYL5CZcjhaI=,tag:aaQ8PNwdlXlQOxC1VDo4Wg==,type:str]
    - name: siaga-db-ai
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:1Ade4RWlByE=,iv:GUGhFG3DZiccdmEHxaamA0mb+xcdT6VKE3WMXrdnih4=,tag:piYFhYctldi8+pfIKPNYwg==,type:str]
        password: ENC[AES256_GCM,data:ieGWSKgjd59HcE6KDfZjzB4Qg7UW4VUqG68RYLh4Zurs/LNwfKhDgUhX7Idc1yhv,iv:s6KVhOUbhLlAL/7CnxR6bnjBEsuDfiZf6iWukwLlAb4=,tag:4msDsHAZqxO1wqYMib9dOw==,type:str]
    - name: siaga-db-tiles
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:sp937USaBR0uUt4=,iv:NtJ97N1fzPLdFCKCDIIXd2vO5lsKmoR6Bh5mA+V9Efc=,tag:od6pFY9CouBVFeNNJqncCA==,type:str]
        password: ENC[AES256_GCM,data:5qOT7AYQP0c2E1I7adq3FK1ioKzfHm0p4k1IPTpiJZV1iuLg01KMCzZ/8kJujhTQ,iv:uvPgysl7mwcxD3PA5agg8nle3pQg9ya4FAZN7yi57hA=,tag:n1Y7CYN/yo8uWlyJnBpQlA==,type:str]
    - name: siaga-garage
      stringData:
        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:HWNQ4ca+WX528jK4tuJWE9ySbh9UENgmaSKQnRxRLBslSRizHIhHnet6vLAKo1pWneCAHgINoxMUF0pBpSKrIA==,iv:90DnT1Us7Nu5rx23JxqSetR21rvwRCkxLwYy7NmoRvA=,tag:8HY3qB3IHe0CMGDN045Dlg==,type:str]
        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:1ueYZHvcVBG1U3rG7BZ+u+KcI/okcxKyhVNrZtVRWuYlsAG5pFW3uUV4U6ZIGPVF,iv:Atw9JzdLxrULRqyumqgaqEdHnCNUlF+m2xd46nMQnY8=,tag:7m7rnG9tqpMt6K5gSGU4BQ==,type:str]
        GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:jnhSjdECLclPYUja7ijpBeA1osX7cBCbxh5YFFVmCehsWY2TdqOS3eFK/yDqRiS6,iv:jF3Zj4l/5uW5uFa9C1s7lHXOEhd05UAbpYH/If6z9m8=,tag:Xe9fL2RsFiJdSD3MU22vKQ==,type:str]
        GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:0XbbqMrCz6+xJwtrsJv9TziiF4tlYOShoT4=,iv:2K7j7Qco0ua9SBiTVgk8an0J+VN4uoLtUsPxwyg3Y7o=,tag:UT5ywSL+lYFTyFPJLMcl6g==,type:str]
        GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:PzJUxDFj1GDHtV1mYiibnKBae4X9fqEjr1VCps5+CIhIrk85sIFL0cdj2HWgA3U/ReghFs36L0MpePa+TmvNYg==,iv:OtCT3wre6OhQ4cHYp0GrWPXtDyu+Lc5Rqls/9oi3PxE=,tag:sR9QYsgzVJ92dwfqPrKD0A==,type:str]
    - name: siaga-ingest
      stringData:
        OPENAQ_API_KEY: ENC[AES256_GCM,data:2cQ3m3+qFJrlFvb89hUDwFGLVcLU/169sk9MhVpw8vCwrPpX2D2Qq5mtAlNitYEk//5oGR1SGlh9IY1c8KrgRw==,iv:EK5SgyDnWu0+0DGeeqs6ZVBJv2vnyuS2SNML2X3BT9Y=,tag:LuvIRtzgrD5Em/yG0PGVfA==,type:str]
        FIRMS_MAP_KEY: ENC[AES256_GCM,data:XxUnLFTdA4tmI2JSpUX58Rp5V4JJ/RkNQQIYzeWwlBY=,iv:9U4UadIfWrnsfPdDi+EYTcC+1XFqet3B7tikSKNDUus=,tag:ay/MIcGEpXB9sZl53pJZqA==,type:str]
    - name: siaga-otel-collector
      stringData:
        OTLP_UPSTREAM_ENDPOINT: ENC[AES256_GCM,data:Np5wUybMfycfyVNSPncUcaZ2aRqYdAMv8kw5Cc4beD0kdNobcCwFEdp7FmKA3ygJ7ymubkQSR9sU,iv:4BZ324z2P14+qv+2s0wrqgoWe6bj/FRQMZwAtR4ic3w=,tag:aP/0sYI93ECCJ+dsjGGfJQ==,type:str]
        OTLP_UPSTREAM_AUTHORIZATION: ENC[AES256_GCM,data:WonkVcEvXnDIIq/VJkohK5MB0j8VDU673e3rpo8eDPSFDN+3AIr3VsCe5ciomi1hwFFoRdCOb4aV9dM1XDdqy7jNwd2lYd1SpMHRVAQ3200D1B+56oF6CHUmf1Abe2O0f+QpEC4ww9+YJmh6z05XPvRWGNhElAWOcVQxbtAmFcvgdRwRRI/q01WgWtkSxOdnEpQmzQMkywHxFUmk8M5KLdu4CeU+Pyr+5Q3FNavCkUcqQXQeUIFHKBizugDxWFg7kr/CJR92RihcX0KVEa5Zwx7DtrJvAUrrwlkP7Ki8MxPc5JRH+6kt+x/C/KfG+A==,iv:zC6QquNIL6puj1Q8uYXhOBlLsaUZyrfLdr3H8MhYcpY=,tag:G0fnhzI+wDHD2GsfySZc8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb1lpY0c2cWtJK1RNSjJo
        WE12YmVmeUkrekRGY2VsMWZkenpwYUlCL0hzCnF4MWJMQmRiKy9odXFOWHppTzRC
        TzUxdm91RXZwc1UrWlR2dlZkamJOdDAKLS0tIFdYdXpnbW9hR0lzandRaHVXQ0Ro
        dnk4SHhpNmwyU2FIOUZ3OFZPY05uTmcKyEWM94OuGqmE23AuykQbIABJtXlF42tC
        0/kAlnhDcIRpjHp865DJvHqxdyag4Onp+JYvQRgy9O0ptCfzISE1zA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zm7j84cz6ep8k5d9xzclcw462aasq80xyx539g2vt9nc64ym3svsktqg5c
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T15:54:53Z"
  mac: ENC[AES256_GCM,data:/GJKlYk9dqtEYXOe7COaAJljDlGzpQtzsHgRFTa/9IhzZm6PNHX7ItpwqhK1yfoVbcUnAYRALJ8ZSVw0rKeHeC7lHOIodEIOq/5PqdctCqLyJiYsL1gaNCXi7sHSVO/YVe5jjC1hef2tNhEy2H/QUS/jdUUc2EN6Is+9sRSwzCo=,iv:05j5mL569QMOTZh/qF/NGftl5PF6iT4K7yg/5c8957A=,tag:Z4r71spyQDkYq41rxs3g8w==,type:str]
  version: 3.13.3
