apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: siaga-secrets
spec:
  secretTemplates:
    - name: siaga-db-geo
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:OYJ7HmAY78d5,iv:JSJF1PoH1kHcBxBgoCL4xLsaMWrw/GC2pBUG7Mnrnn8=,tag:zOg/2fsbksdu9L89OAg4HA==,type:str]
        password: ENC[AES256_GCM,data:bd3ZgdPutPllcJwMuMaglFD022Ss9Rjn5C7vEhZSfVh8/b0Z1dJvhHSqMvpPKScF,iv:HPJ6X2My3E9EQU8pWYhn1A3TgtSLnI8qdWufB0l1Uus=,tag:y3wChypo+sP9zReq8JjaTw==,type:str]
    - name: siaga-db-core
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:LpLFyC1SSL2e8g==,iv:RXNKGsNvviFP2kg3HrggANBw1LB2/owtbzYOEy9vRac=,tag:/4dphxK+HJF15ADi6OZzPQ==,type:str]
        password: ENC[AES256_GCM,data:wXrn0VhEYpTtZDRLDLmq4NjSpGcfEVFqzY91TeJLhXwgT3P94/qn87sHB6W+a3Hw,iv:jHl3dDJQ6VZY0DFZEFUWIlOw2F0WwdRGAXxNgIzfr9I=,tag:kb5wH6Zsn7+Ri3j+9utnCw==,type:str]
    - name: siaga-db-alert
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:AvqJ0PTmBCKnefk=,iv:cLzNO4m+TYHe+1Tj4qtGfXA7CP08bovy/3hoVDJDYjY=,tag:YrjXjcAthzRuysKXJdq5Gg==,type:str]
        password: ENC[AES256_GCM,data:SiBTWg4gLk0OnQEFfXWDq5VG0qD/JGlJYq1Rtjb4z81hbzzKTaR+CtSILi3nuWby,iv:W0wonQPmc40WS/nShcQ6Acx5PHkErOPkKMadGDxlxa4=,tag:D5ldaUQ0VTW1T0ph2ufDIQ==,type:str]
    - name: siaga-db-ai
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:fqQBNRw4VCs=,iv:z0yZh2Odim3LnyoMB37xuvx/OxsDuKYSHLVhBxu0BqE=,tag:xRzpr+3VpzVdoG3guqUzBw==,type:str]
        password: ENC[AES256_GCM,data:Nwkc5H0Rkhmhn0q8Fz55WyrW7JRwad1rWLveHdyqKMlUvt47EzW+VbnmbKdmFBAk,iv:bbtFIOGU6fZ1YljepMX4G0/wKnq2osJ3C2DiOnNc7wY=,tag:8dQH35HkviDzorwoUagFBQ==,type:str]
    - name: siaga-db-tiles
      type: kubernetes.io/basic-auth
      labels:
        cnpg.io/reload: "true"
      stringData:
        username: ENC[AES256_GCM,data:qipJQE6t5LIJxQU=,iv:fmnlEdQOpsKYj2Y2Bd66yWJhIcfk0ZX/QfklzWaL7ls=,tag:qgbRglfXZp7zIzpYrwkTGQ==,type:str]
        password: ENC[AES256_GCM,data:XEwB9CA0FQAEUrbNXz1G0yWY9lsKvqdm6a6vwWLWICB7G39hIDWU0Uii18bErcUA,iv:CMwH0LnnX0tlCAfKqNYl3kGJrmaF9A2jofGtkEImCJQ=,tag:+QcznaqH0opOXY3S192mTg==,type:str]
    - name: siaga-garage
      stringData:
        GARAGE_RPC_SECRET: ENC[AES256_GCM,data:WjmpieLifC5Bw8iAsrsoOa9loPFYAAqy89c9hiy+zrZwNkDB20l1+8+F5XYxL+ZikqAmMl09JED8eFDNtK51PQ==,iv:N2YhtpFdY7S/EV5tGTvboDGhCk0EDySpQLtTlMUlSGQ=,tag:sPlyqr6+oZO9na/jy6KSAg==,type:str]
        GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:QP7KrGh3p3KIintEXeDC8pXrb8oViTxHdQ1wVjdGhppmHz3d0qL8DiatkLxmVJFB,iv:3DBsj3D7qkvzyGeb9j/pcXk0xHR/bQ9DS7uG4LRkW5Y=,tag:rP4T9YAAXPUENLslqHHAFg==,type:str]
        GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:5cxa8arjQ52rrPZGwtt7D8IiJQ243UrF8yGlLeaBWEv1HWdIz4Jb9xQuFNioxMho,iv:axoOkrERjcEuqoXYBJUGJdkv0sSHdtpNzBLsCm+683Q=,tag:/FtPDsSk7e0fdZMy9+i0rw==,type:str]
        GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:A2iymELgnGxjvut75xL971QMe5aZz/TEX7k=,iv:8x1T8NFaYlI5xvxPbfbCLxEwpPZeg2RXOr8xnE7dHE8=,tag:+FOWztg3fQmLvVZs2wBzUg==,type:str]
        GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:bM/P1MOSgO83lhFHy6j80EoslfCOhYolChP2nl7zOIR8RQ9Yl6PABezbhpbFQ7v8QVjbWU0N8w89WPpjwoJNVg==,iv:M0B8atbP9TSaHE6ny5VYWy93rJ1x+I3dhhEkky0dhqs=,tag:lTAAVFTDhLW8GU7ZDGdsYQ==,type:str]
    - name: siaga-ingest
      stringData:
        OPENAQ_API_KEY: ENC[AES256_GCM,data:spjcKQWF8OHSyxoW89OESWxXtM3tUVg9YVrVmkG6zzthh+kJ/nJpD18ml2pUfNwave3I3CWBitwSRAI6KkEqsA==,iv:/pP0rULoG1voXaiu+QHQhHU8GEhFIZ7Lo2kKHNdAE/0=,tag:i0k/Jcq9C/7lESfIbNbCJw==,type:str]
        FIRMS_MAP_KEY: ENC[AES256_GCM,data:fzQnrKWliBliHT9PEs46XkfGd3JwWSE3ip2XAeDKOxo=,iv:vIJDgHOLf7FiwLdkTZxu+J1wSNZRoypztSkwITdfrRg=,tag:OEVu7EneO7M5/7sWhcWGkQ==,type:str]
    - name: siaga-otel-collector
      stringData:
        OTLP_UPSTREAM_ENDPOINT: ENC[AES256_GCM,data:cjFX8UK7BjikHZwq0xysg4Eubc+AhhWyWlir4RIk4L6EJ/bXKgNHV/rSb9tcmaVHH47jx2l830wL,iv:O+BNvNFN2Iw4jdzHLT/1DGk6vlNR9qUFqoIOViHg0Wk=,tag:+ijEDHHh0/dh29H5wA27xA==,type:str]
        OTLP_UPSTREAM_AUTHORIZATION: ENC[AES256_GCM,data:FLDazGB0BQSjCyP7/CzjsyUPKLPJepVOzMk3S0kfGE8XhgQ8qXOvdiDk6pqLOENSW1fDQlpOiEsKYjZzOIOAOUX7RSU+z4ZXMI2UksIXDDalwwg6iu0krIFZK36Qvn+GLKyuxbNHIkjtaJYpSVHbfRqgOm4OVCt3CJ7sqFYgjY89civk0170qB33+DcmnB96HjGV9p5X+dnYxN9QYIFxopcEEgzo9xm8Bsj3qPvW6EwhgzD8VjP8hO0J/Lerm0FaDIr50STTNZNIvwUYtUWQ2Ukf,iv:wHFv17ubHSIs7Hk5RJXs+P0pj7+QIPS2hdnZHvtjjmY=,tag:UkCUdNw/KX2LjgIe0lSjIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K2cxNWlaV0swNVdiYTBK
        dHlvYTVkcStFdWp0TTNsRTJsanRMazJLblFFCnlaUlp6M3QyUEVLWG1uRjVZNXVY
        YU11eUdPNXpTNGVqb3dpb25kdEI4NDAKLS0tIGNITkZqYnNLM3J3aVRuU3JoUkZB
        MThCcXhkNG4ydkkwYVlWdDZYTDBSMWMKeYQWKI/4B6CGNWAcyq9a26pzppqV3Myi
        XX4Srdhe3f4yOc7h5AgYJZUnuhqG5b44F34ABpojCYfUlMBw9+/EOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zm7j84cz6ep8k5d9xzclcw462aasq80xyx539g2vt9nc64ym3svsktqg5c
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T14:58:38Z"
  mac: ENC[AES256_GCM,data:8xIT0qV1StKiA1Vqo2v7HtUuaY2GoxXrDwxOaqEfB3WlvFLESQNdmFdJAxFG+1x3bW2wpfANsW20RI/MNDXq0GKHQ3O9Bwz4398j9QH9Q+XSmYu8Y89sCdy/jYyLhq6MfDVLrAnSkm4svYIUKDahgjB1TM2btYVTuxSuGuc+/8w=,iv:eGUEeJo7dRjubM55cd28VVS0IoHvuaxDCKUIRTJPet0=,tag:0BMDOhVDMeMQX1g9V7LBIw==,type:str]
  version: 3.13.3
